routes:
  login:
    route: /login
    method: POST
    controller: App\Controllers\AuthController@login
    request: login

  test:
    route: /test
    method: POST
    controller: Mvc\TestController@test
    request: test

  put:
    route: /test_put
    method: PUT
    controller: Mvc\TestController@test

  delete:
    route: /test_delete
    method: DELETE
    controller: Mvc\TestController@test

  no_request:
    route: /no_request
    method: GET
    controller: Mvc\TestController@no_request

  bad_request:
    route: /bad_request
    method: GET
    controller: Mvc\TestController@bad_request
